# JDBC driver class
jakarta.persistence.jdbc.driver=org.h2.Driver

# JDBC connection URL
jakarta.persistence.jdbc.url=jdbc:mysql://localhost:3306/reservation_dev

# DB credentials
jakarta.persistence.jdbc.user=student
jakarta.persistence.jdbc.password=student

# Hibernate dialect
hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
hibernate.show_sql=true
hibernate.format_sql=true
